import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import * as stylex from "@stylexjs/stylex";

import { colorScheme } from "@/lib/themes";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// color-scheme on <html> (OS by default, data-theme forces a mode) picks a
// side of every light-dark() color token; portaled popups inherit it. Its
// className joins next/font's classes, since <html> takes one className.
const scheme = stylex.props(colorScheme);

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${scheme.className}`}
    >
      <body>{children}</body>
    </html>
  );
}
