import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { afterEach, beforeEach, expect, test, vi } from 'vitest';

import { applyPageStyles } from '../src/page-styles.ts';

const THEMES = 'export const colorScheme = {};\nexport const page = {};\n';

// create-next-app 16 `app` template.
const NEXT_LAYOUT = `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={\`\${geistSans.variable} \${geistMono.variable}\`}>
      <body>{children}</body>
    </html>
  );
}
`;

let cwd: string;
const read = (rel: string) => fs.readFileSync(path.join(cwd, rel), 'utf8');
const write = (rel: string, content: string) => {
  fs.mkdirSync(path.dirname(path.join(cwd, rel)), { recursive: true });
  fs.writeFileSync(path.join(cwd, rel), content);
};

beforeEach(() => {
  cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'madeui-layout-'));
  vi.spyOn(console, 'log').mockImplementation(() => {});
});

afterEach(() => {
  vi.restoreAllMocks();
  fs.rmSync(cwd, { recursive: true, force: true });
});

test('Next: puts colorScheme on <html> and page on <body> in the create-next-app layout', () => {
  write('lib/themes.ts', THEMES);
  write('app/layout.tsx', NEXT_LAYOUT);
  const changed: string[] = [];

  const steps = applyPageStyles(cwd, 'next', 'lib', changed);

  expect(steps).toEqual([]);
  expect(changed).toEqual(['app/layout.tsx']);
  const layout = read('app/layout.tsx');
  expect(layout).toContain(
    `import "./globals.css";\nimport * as stylex from "@stylexjs/stylex";\nimport { colorScheme, page } from "../lib/themes";\n`
  );
  expect(layout).toContain(
    '<html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${stylex.props(colorScheme).className}`}>'
  );
  expect(layout).toContain('<body {...stylex.props(page)}>{children}</body>');
});

test('imports through the "@/*" path alias when tsconfig maps it over the lib folder', () => {
  write('lib/themes.ts', THEMES);
  write('app/layout.tsx', NEXT_LAYOUT);
  write('tsconfig.json', '{\n  "compilerOptions": {\n    // comment\n    "paths": {\n      "@/*": ["./*"]\n    }\n  }\n}\n');
  write('src/lib/themes.ts', THEMES);
  write('src/main.tsx', "import './index.css'\n");
  write('tsconfig.app.json', '{ "compilerOptions": { "paths": { "@/*": ["./src/*"] } } }\n');

  applyPageStyles(cwd, 'next', 'lib', []);
  applyPageStyles(cwd, 'vite', 'src/lib', []);

  expect(read('app/layout.tsx')).toContain('import { colorScheme, page } from "@/lib/themes";');
  expect(read('src/main.tsx')).toContain("import { colorScheme, page } from '@/lib/themes'");
});

test('Next: appends to string and multi-line className attributes', () => {
  write('lib/themes.ts', THEMES);
  write(
    'app/layout.tsx',
    `import "./globals.css";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={\`\${geistSans.variable} h-full antialiased\`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
`
  );

  expect(applyPageStyles(cwd, 'next', 'lib', [])).toEqual([]);
  const layout = read('app/layout.tsx');
  expect(layout).toContain(
    '      className={`${geistSans.variable} h-full antialiased ${stylex.props(colorScheme).className}`}\n    >'
  );
  expect(layout).toContain(
    '<body className={`min-h-full flex flex-col ${stylex.props(page).className}`}>{children}</body>'
  );
});

test('Next: a className it cannot extend leaves the layout alone and prints the snippet', () => {
  write('lib/themes.ts', THEMES);
  const layout = `export default function RootLayout({ children }) {
  return (
    <html lang="en" className={fonts}>
      <body>{children}</body>
    </html>
  );
}
`;
  write('app/layout.js', layout);
  const changed: string[] = [];

  const steps = applyPageStyles(cwd, 'next', 'lib', changed);

  expect(read('app/layout.js')).toBe(layout);
  expect(changed).toEqual([]);
  expect(steps).toHaveLength(1);
  expect(steps[0]).toContain('app/layout.js');
  expect(steps[0]).toContain("import { colorScheme, page } from '../lib/themes';");
  expect(steps[0]).toContain('<html {...stylex.props(colorScheme)}>');
  expect(steps[0]).toContain('<body {...stylex.props(page)}>');
});

test('Next: a second run leaves an applied layout alone', () => {
  write('lib/themes.ts', THEMES);
  write('app/layout.tsx', NEXT_LAYOUT);
  applyPageStyles(cwd, 'next', 'lib', []);
  const once = read('app/layout.tsx');
  const changed: string[] = [];

  expect(applyPageStyles(cwd, 'next', 'lib', changed)).toEqual([]);
  expect(read('app/layout.tsx')).toBe(once);
  expect(changed).toEqual([]);
});

test('Next: a layout that already applies colorScheme only gets page', () => {
  write('lib/themes.ts', THEMES);
  write(
    'app/layout.tsx',
    `import * as stylex from '@stylexjs/stylex';

import { colorScheme } from '@/lib/themes';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" {...stylex.props(colorScheme)}>
      <body>{children}</body>
    </html>
  );
}
`
  );

  expect(applyPageStyles(cwd, 'next', 'lib', [])).toEqual([]);
  const layout = read('app/layout.tsx');
  expect(layout).toContain(
    "import * as stylex from '@stylexjs/stylex';\n\nimport { colorScheme, page } from '@/lib/themes';\n\nexport"
  );
  expect(layout).toContain('<html lang="en" {...stylex.props(colorScheme)}>');
  expect(layout).toContain('<body {...stylex.props(page)}>');
});

test('Vite: adds the classes to <html> and <body> from the create-vite entry', () => {
  write('src/lib/themes.ts', THEMES);
  write(
    'src/main.tsx',
    `import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`
  );
  const changed: string[] = [];

  expect(applyPageStyles(cwd, 'vite', 'src/lib', changed)).toEqual([]);
  expect(changed).toEqual(['src/main.tsx']);
  expect(read('src/main.tsx')).toBe(`import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'
import * as stylex from '@stylexjs/stylex'
import { colorScheme, page } from './lib/themes'

// Page styles from lib/themes.ts: colorScheme on <html>, page on <body>.
document.documentElement.classList.add(...(stylex.props(colorScheme).className?.split(' ') ?? []))
document.body.classList.add(...(stylex.props(page).className?.split(' ') ?? []))

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
`);

  applyPageStyles(cwd, 'vite', 'src/lib', changed);
  expect(changed).toEqual(['src/main.tsx']);
});

test('Vite: no entry file prints the snippet', () => {
  write('src/lib/themes.ts', THEMES);

  const steps = applyPageStyles(cwd, 'vite', 'src/lib', []);

  expect(steps).toHaveLength(1);
  expect(steps[0]).toMatch(/no src\/main/);
  expect(steps[0]).toContain('document.body.classList.add(');
});

test('Next: a style already imported from themes counts as applied, however it is used', () => {
  write('lib/themes.ts', THEMES);
  write(
    'app/layout.tsx',
    `import * as stylex from "@stylexjs/stylex";

import { colorScheme } from "@/lib/themes";

const scheme = stylex.props(colorScheme);

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={\`\${font.variable} \${scheme.className}\`}>
      <body>{children}</body>
    </html>
  );
}
`
  );

  applyPageStyles(cwd, 'next', 'lib', []);
  const layout = read('app/layout.tsx');
  expect(layout).toContain('import { colorScheme, page } from "@/lib/themes";');
  expect(layout).toContain('<html lang="en" className={`${font.variable} ${scheme.className}`}>');
  expect(layout).toContain('<body {...stylex.props(page)}>');
});

test('Next: a tag named in a comment is not mistaken for the element', () => {
  write('lib/themes.ts', THEMES);
  write(
    'app/layout.tsx',
    `// Fonts go on <html> so portals inherit them.
export default function RootLayout({ children }) {
  /* <body> stays plain */
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
  );

  applyPageStyles(cwd, 'next', 'lib', []);
  const layout = read('app/layout.tsx');
  expect(layout).toContain('// Fonts go on <html> so portals inherit them.');
  expect(layout).toContain('/* <body> stays plain */');
  expect(layout).toContain('<html lang="en" {...stylex.props(colorScheme)}>');
  expect(layout).toContain('<body {...stylex.props(page)}>');
});

test('Next: a tag that already spreads props is left alone (a second className would replace it)', () => {
  write('lib/themes.ts', THEMES);
  const layout = `import * as stylex from '@stylexjs/stylex';

import { brandTheme } from '@/lib/brand';

export default function RootLayout({ children }) {
  return (
    <html lang="en" {...stylex.props(brandTheme)}>
      <body>{children}</body>
    </html>
  );
}
`;
  write('app/layout.tsx', layout);

  const steps = applyPageStyles(cwd, 'next', 'lib', []);

  expect(read('app/layout.tsx')).toBe(layout);
  expect(steps).toHaveLength(1);
});

test('Next: an aliased import counts as applied', () => {
  write('lib/themes.ts', THEMES);
  write(
    'app/layout.tsx',
    `import * as stylex from '@stylexjs/stylex';
import { colorScheme as scheme } from '../lib/themes';

export default function RootLayout({ children }) {
  return (
    <html lang="en" {...stylex.props(scheme)}>
      <body>{children}</body>
    </html>
  );
}
`
  );

  applyPageStyles(cwd, 'next', 'lib', []);
  const layout = read('app/layout.tsx');
  expect(layout).toContain("import { colorScheme as scheme, page } from '../lib/themes';");
  expect(layout).toContain('<html lang="en" {...stylex.props(scheme)}>');
  expect(layout).toContain('<body {...stylex.props(page)}>');
});

test('Next: another module named themes is not merged into; a named stylex import still gets the namespace', () => {
  write('lib/themes.ts', THEMES);
  write(
    'app/layout.tsx',
    `import { props } from '@stylexjs/stylex';
import { ThemeProvider } from '@/components/themes';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
  );

  applyPageStyles(cwd, 'next', 'lib', []);
  const layout = read('app/layout.tsx');
  expect(layout).toContain(
    "import { ThemeProvider } from '@/components/themes';\nimport * as stylex from '@stylexjs/stylex';\nimport { colorScheme, page } from '../lib/themes';\n"
  );
});

test('imports go after a leading directive; Vite statements go after imports that follow a block comment', () => {
  write('lib/themes.ts', THEMES);
  write('app/layout.tsx', `'use client';\n\nexport default function RootLayout({ children }) {\n  return (\n    <html>\n      <body>{children}</body>\n    </html>\n  );\n}\n`);
  write('src/lib/themes.ts', THEMES);
  write('src/main.tsx', `/* Entry */\nimport './index.css'\n\nrender()\n`);

  applyPageStyles(cwd, 'next', 'lib', []);
  applyPageStyles(cwd, 'vite', 'src/lib', []);

  expect(read('app/layout.tsx')).toMatch(/^'use client';\nimport \* as stylex/);
  expect(read('src/main.tsx')).toMatch(
    /^\/\* Entry \*\/\nimport '.\/index.css'\nimport \* as stylex from '@stylexjs\/stylex'\nimport \{ colorScheme, page \} from '.\/lib\/themes'\n\n\/\/ Page styles/
  );
});

test('an older themes.ts without page leaves the layout alone and says how to update it', () => {
  write('lib/themes.ts', 'export const colorScheme = {};\n');
  write('app/layout.tsx', NEXT_LAYOUT);

  const steps = applyPageStyles(cwd, 'next', 'lib', []);

  expect(read('app/layout.tsx')).toBe(NEXT_LAYOUT);
  expect(steps).toHaveLength(1);
  expect(steps[0]).toMatch(/lib\/themes\.ts has no `page` export/);
  expect(steps[0]).toContain('add theme --overwrite');
});

test('Next: no app/layout (pages router) prints the snippet', () => {
  write('lib/themes.ts', THEMES);
  write('pages/_document.tsx', 'export default function Document() {}\n');

  const steps = applyPageStyles(cwd, 'next', 'lib', []);

  expect(steps).toHaveLength(1);
  expect(steps[0]).toMatch(/no app\/layout/);
  expect(steps[0]).toContain('<body {...stylex.props(page)}>');
});
