// The Example map: a generated client module (site/examples.generated.tsx)
// with one `next/dynamic` import per Example, keyed by its `<Component path>`.
// Each Example becomes its own chunk, so a page loads only the Examples it
// renders. A static import would put every Example on every docs page: they
// all share one route.

/** The generated module's source for these Example paths. */
export function renderExampleMap(paths: string[]): string {
  const entries = paths.map(
    (path) => `  ${JSON.stringify(path)}: dynamic(() => import(${JSON.stringify(`@examples/${path}`)})),`,
  );
  return `'use client';

// Generated by scripts/example-map.mts from packages/registry/examples.
// Do not edit; it is rewritten before dev and build and while dev runs.
import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

const examples: Record<string, ComponentType> = {
${entries.join('\n')}
};

/** The live Example a \`<Component path>\` names; nothing for an unknown path. */
export function Example({ path }: { path: string }) {
  const Component = examples[path];
  return Component ? <Component /> : null;
}
`;
}
