import fs from 'node:fs';
import path from 'node:path';

// The Showcase (app/showcase, dev and SHOWCASE=1 builds only): every registry
// component with all its Examples, one section per component. The sections
// come from the registry index and the Examples folder, so the page never
// needs editing when a component or an Example is added.

/** The registry index, generated by `pnpm build:registry`. From process.cwd(), like the Examples folder. */
export const REGISTRY_INDEX = path.resolve(process.cwd(), '../../packages/registry/public/r/registry.json');

export interface ShowcaseComponent {
  /** The registry item name, e.g. `button-group`. */
  name: string;
  /** The registry item title, e.g. `Button Group`. */
  title: string;
}

export interface ShowcaseSection extends ShowcaseComponent {
  /** The `<Component path>` keys of the component's Examples, sorted. */
  examples: string[];
}

/** Every component (registry:ui item) in the registry index, in index order. */
export function registryComponents(index: string = REGISTRY_INDEX): ShowcaseComponent[] {
  const registry = JSON.parse(fs.readFileSync(index, 'utf8')) as {
    items: { name: string; title: string; type: string }[];
  };
  return registry.items.filter((item) => item.type === 'registry:ui').map(({ name, title }) => ({ name, title }));
}

/**
 * One section per component, holding the Examples named after it. An Example
 * belongs to the longest component name it starts with (`button-group-demo`
 * is Button Group's, not Button's). An Example that matches no component
 * throws: it would otherwise be missing from the Showcase unnoticed.
 */
export function showcaseSections(components: ShowcaseComponent[], examples: string[]): ShowcaseSection[] {
  const byName = new Map(components.map((component) => [component.name, [] as string[]]));
  const longestFirst = [...byName.keys()].sort((a, b) => b.length - a.length);
  const unmatched: string[] = [];
  for (const example of [...examples].sort()) {
    const owner = longestFirst.find((name) => example.startsWith(`${name}-`));
    if (owner === undefined) unmatched.push(example);
    else byName.get(owner)!.push(example);
  }
  if (unmatched.length > 0) {
    throw new Error(`Examples named after no registry component: ${unmatched.join(', ')}`);
  }
  return components.map((component) => ({ ...component, examples: byName.get(component.name)! }));
}
